name: FTP Test

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: 📂 Sync files
        uses: ./
        with:
          server: sv2.php.starfree.ne.jp
          username: felica29.starfree.jp
          password: yachin1867//home/felica29

